Improve jira ticket parsing with error message
Echo error to STDERR to make sure it doesn't mess up anything else

diff --git a/local/bin/current-jira-ticket b/local/bin/current-jira-ticket
--- a/local/bin/current-jira-ticket
+++ b/local/bin/current-jira-ticket
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 
+set -e
+
 branch_name=$(git rev-parse --abbrev-ref HEAD)
 
 if [[ "$branch_name" =~ [A-Z]+-[0-9]+ ]]; then
   echo "$branch_name" | perl -pe "s|^.*?([A-Z]+-[0-9]+).*$|\1|"
 else
+  >&2 echo "Can't parse JIRA ticket from branch '${branch_name}'"
   exit 1
 fi
